version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - yarn install
  pre_build:
    commands:
      - echo "Running build script..."
      - chmod +x ./build.sh
      - ./build.sh
  build:
    commands:
      - echo "Starting build process..."
      - echo "NEXT_PUBLIC_OPENAI_API_KEY=$NEXT_PUBLIC_OPENAI_API_KEY" >> .env
      - echo "NEXT_PUBLIC_MUSIC_API=$NEXT_PUBLIC_MUSIC_API" >> .env
      - echo "NEXT_PUBLIC_MUSIC_API2=$NEXT_PUBLIC_MUSIC_API2" >> .env
      - echo "NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID" >> .env
      - sudo chown -R $USER:$GROUP ~/.npm
      - sudo chown -R $USER:$GROUP ~/.config
      - yarn run build
  post_build:
    commands:
      - echo "Setting permissions for server pages..."
      - sudo chown -R $USER:$GROUP /codebuild/output/src2754623343/src/emotional/.next/server/pages
      - sudo chmod -R 775 /codebuild/output/src2754623343/src/emotional/.next/server/pages
