version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - yarn install
  pre_build:
    commands:
      - echo "Running build script..."
      - chmod +x ./build.sh
      - ./build.sh
  build:
    commands:
      - echo "Starting build process..."
      - yarn build
