export const Meta = {
  title: 'emotional',
  siteName: 'emotional',
  description:
    '자신의 감정을 표현하면 그에 맞는 추천 노래 Playlist를 알려드려요.',
  keywords: [
    '일기',
    '감정',
    '감정적인',
    '감성',
    '감성적인',
    '노래',
    '음악',
    '추천',
    'playlist',
    'youtube',
    '알고리즘',
    'ai',
    'gpt',
    '유튜브',
    '플레이리스트',
    'playlist 추천',
    'playlist추천',
    '플레이리스트 추천',
    '플레이리스트추천',
    '노래 추천',
    '노래추천',
    '음악 추천',
    '음악추천',
    'emotional',
    '이모셔널',
    'music',
  ],
  url: 'https://www.emotional.today/',
  naverVerification: 'cde8956ade8797ebd60205e32864a43ffad92e24',
  image: '/og-imgae.jpg',
};
